name: CI/CD

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Start containers
      run: docker-compose -f "docker-compose.yaml" up -d --build
      env:
        POSTGRES_USER: postgre #${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: postgre #${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: bi_cur #${{ secrets.POSTGRES_DB }}
        POSTGRES_CONNECTION_STRING_AUTH: "postgresql+psycopg2://postgre:postgre@host.docker.internal:5434/bi_cur"
        POSTGRES_CONNECTION_STRING_FIELDS: "postgresql+psycopg2://postgre:postgre@host.docker.internal:5433/bi_cur"
        POSTGRES_CONNECTION_STRING_PROGRAMS: "postgresql+psycopg2://postgre:postgre@host.docker.internal:5432/bi_cur"
        FIELDS_URL: http://host.docker.internal:82/fields/
        PROGRAMS_URL: http://host.docker.internal:82/programs/fields
        AUTH_URL: http://host.docker.internal:82/auth/session/check
        API_TOKEN: 31620f51972845091649802035b423d1 #${{ secrets.API_TOKEN }}
        SECRET: 123456789 #${{ secrets.SECRET }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r tests/requirements.txt
        
    - name: Run tests
      run: pytest tests/test_api.py
      env:
        API_URL: http://localhost:82