name: CI/CD

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bi_cur

        ports:
          - 5434:5432

    steps:
    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install --yes postgresql-client

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute auth sql script
      #run: psql -h postgres -d postgres_db -U postgres_user -c 'SELECT 1;'
      run: psql -h 0.0.0.0 -p 5434 -U postgres -d bi_cur -f auth/db_init/init.sql
      env:
        PGPASSWORD: postgres
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    
    - name: Setting variables
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        SECRET: ${{ secrets.SECRET }}
      run: echo "$API_TOKEN"

    - name: Install dependencies
      run: |
        pip install -r auth/app/requirements.txt
        pip install -r fields/app/requirements.txt
        pip install -r programs/app/requirements.txt
        
    - name: Build Docker images
      run: |
        docker build -t auth ./auth/app
        docker build -t fields ./fields/app
        docker build -t programs ./programs/app
